---
- hosts: nodes
  serial: 1
  gather_facts: no
  connection: local
  vars:
    iDRAC_resource_path1: "/redfish/v1/Managers/iDRAC.Embedded.1/Attributes"
    iDRAC_user: "root"
    iDRAC_pass: "iDRAC_Password"
    body1: '{"Attributes":{"SysLog.1.SysLogEnable":"Enabled","SysLog.1.Server1":"Syslog_Server","SysLog.1.Port":514}}'
    body2: '{"Attributes":{"NTPConfigGroup.1.NTPEnable":"Enabled","NTPConfigGroup.1.NTP1":"NTP_Server"}}'

  tasks:
  
  - name: configuration syslog on iDRAC VxRAIL node 
    uri:
      url: https://{{ inventory_hostname }}{{ iDRAC_resource_path1 }} 
      method: PATCH
      validate_certs: no
      use_proxy: no
      status_code: 200
      user: "{{ iDRAC_user }}"
      password: "{{ iDRAC_pass }}"
      force_basic_auth: yes
      body_format: json
      body: "{{ body1 }}" 
    delegate_to: localhost
    register: iDRACK_Syslog_Configuration

  - name: configuration NTP on iDRAC VxRAIL node
    uri:
      url: https://{{ inventory_hostname }}{{ iDRAC_resource_path1 }} 
      method: PATCH
      validate_certs: no
      use_proxy: no
      status_code: 200
      user: "{{ iDRAC_user }}"
      password: "{{ iDRAC_pass }}"
      force_basic_auth: yes
      body_format: json
      body: "{{ body2 }}" 
    delegate_to: localhost
    register: iDRACK_NTP_Configuration
